copy button
Ludium-Official/ludium-world-front-end pull request #6
Opened 2024-06-05 14:06 UTC by dongkyun2331

코드블록 복사버튼
![Screenshot from 2024-06-05 22-58-55](https://github.com/Ludium-Official/ludium-world-front-end/assets/119479530/d5beca9c-d6f1-4046-b4b7-3dd8de14be34)

2024-06-07 13:43 UTC, IDKNWHORU requested changes

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +        document.querySelectorAll('pre').forEach((pre) => {
1. for-each => for-of로 변경해줘
2. 변수명은 pre => codeBlock로 바꿔줘

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +          button.innerText = '복사';
1. 인라인 스타일(button.style...) 대신에 [class 선택자](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)를 만들어줘.
2. class 선택자는 [global.css](https://github.com/Ludium-Official/ludium-world-front-end/blob/main/provider/app/global.css) 파일에 새로 정의하면 돼

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +          pre.appendChild(button);
1. button 부모 엘리먼트 buttonWrapper(div)를 만들어줘 pre > buttonWrapper(div) > button 형태로 나타나야돼.
2. buttonWrapper는 이미 정의되어 있는 "flex-end"(global.css에 있음)라는 class 선택자를 이용할 수 있게 해줘.
3. codeBlock(pre) 제일 첫번째 자식으로 `buttonWrapper`를 추가해줘. [insertBefore](https://yari-demos.prod.mdn.mozit.cloud/ko/docs/Web/API/Node/insertBefore)를 사용하면 돼

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +          button.style.position = 'absolute';
absolute 관련 스타일은 없애줘

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +          pre.style.position = 'relative';
position 정의는 필요없음

2024-06-07 13:43 UTC, IDKNWHORU commented on provider/components/Viewer.jsx
> +          button.innerText = '복사';
문자열은 전부 쌍 따옴표(")로 통일해줘

2024-06-08 10:04 UTC, dongkyun2331 commented
완료

2024-06-08 12:21 UTC, merged